name: Enhancement
description: Improve an existing feature
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: teamarr-version
    attributes:
      label: Teamarr Version
      description: Which version does this apply to?
      options:
        - V1 (stable)
        - V2 (alpha)
        - Both / Either
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
      placeholder: How it works now
    validations:
      required: true

  - type: textarea
    id: improvement
    attributes:
      label: Proposed improvement
      placeholder: How it should work instead
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Why?
      placeholder: What's the benefit?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, examples
